inherit_from: .rubocop.todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'lib/templates/**/*'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

# Relates to the indentation of if/when/(etc.) blocks when the initial keyword
# is indented as part of a variable assignment.
#
# Our preference is that the rubocop default conflicts with our 80-character
# line restriction, leaving less space for code inside nested blocks. We make
# this change at the cost of a little bit of readability.
#
#     # bad (although the Rubocop default):
#     thing = if x > 42
#               thing!
#             else
#               other_thing!
#             end
#
#     # good (preferred):
#     thing = if x > 42
#       thing!
#     else
#       other_thing!
#     end
#
#     # also acceptable
#     thing =
#       if x > 42
#         thing!
#       else
#         other_thing!
#       end

# There *are* places where long lines are tolerated, because the alternative is
# too hideous to think about
Metrics/LineLength:
  Exclude:
    - config/routes.rb

# Passing multiple hashes to a function is messy, and clarity is good
# This is an extension of https://github.com/bbatsov/ruby-style-guide#no-braces-opts-hash
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
  StyleGuide: https://github.com/bbatsov/rubocop/issues/801

# This is one part of the style guide that doesn't express a preference, it just
# suggests you make a choice
Style/DotPosition:
  EnforcedStyle: trailing

Style/StringLiterals:
  EnforcedStyle: double_quotes
  StyleGuide: https://www.viget.com/articles/just-use-double-quoted-ruby-strings
